import { readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";

import { format, resolveConfig } from "prettier";

import { readBacklog } from "./lib/backlog.mjs";

const root = process.cwd();
const templatePath = join(root, "scripts", "templates", "backlog.html");
const outputPath = join(root, "docs", "backlog", "backlog.html");
const check = process.argv.includes("--check");
const { backlogDir, stories, sprints } = await readBacklog(root);

if (sprints.length !== 1) {
  throw new Error(`The dashboard currently requires exactly one sprint; found ${sprints.length}.`);
}

const storyById = new Map(stories.map((record) => [record.data.id, record]));
const sprint = sprints[0].data;
const sprintStoryIds = new Set(sprint.story_ids);
const sprintStories = stories
  .filter(({ data }) => sprintStoryIds.has(data.id))
  .map((record) => {
    const story = record.data;
    return {
      id: story.id,
      productPath: relative(backlogDir, record.path).replaceAll("\\", "/"),
      status: story.status,
      order: story.order,
      hours: story.estimate_hours,
      tasks: story.tasks.map((task) => ({
        id: task.id,
        title: task.title,
        role: task.role,
        status: task.status,
        hours: task.estimate_hours,
        assignees: task.assignees,
      })),
      title: story.title,
      description: story.description,
      epic: story.epic,
      assignees: story.assignees,
    };
  });

for (const storyId of sprint.story_ids) {
  if (!storyById.has(storyId)) throw new Error(`${sprints[0].file}: unknown story ${storyId}`);
}

const data = {
  product: stories.map(({ data: story }) => ({
    id: story.id,
    title: story.title,
    description: story.description,
    epic: story.epic,
    role: story.role,
    status: story.lifecycle,
    points: story.story_points,
    criteria: story.acceptance_criteria,
  })),
  dependencies: Object.fromEntries(
    stories.map(({ data: story }) => [story.id, story.dependencies])
  ),
  sprint: {
    id: sprint.id,
    label: sprint.id
      .split("-")
      .map((part) => `${part[0].toUpperCase()}${part.slice(1)}`)
      .join(" "),
    goal: sprint.goal,
    start: sprint.dates.start,
    end: sprint.dates.end,
    status: sprint.status,
    hours: sprint.capacity_hours,
    stories: sprintStories,
    tasks: sprintStories.reduce((total, story) => total + story.tasks.length, 0),
  },
};

const template = await readFile(templatePath, "utf8");
const dataBlockPattern = /<script id="backlog-data" type="application\/json">[\s\S]*?<\/script>/;
if (!dataBlockPattern.test(template))
  throw new Error(`${templatePath}: missing backlog data block`);
const serializedData = JSON.stringify(data, null, 2).replaceAll("<", "\\u003c");
const dataBlock = `<script id="backlog-data" type="application/json">\n${serializedData}\n</script>`;
const prettierConfig = (await resolveConfig(outputPath)) ?? {};
const rendered = await format(
  `<!-- Generated by npm run backlog:build. Do not edit directly. -->\n${template.replace(dataBlockPattern, dataBlock)}`,
  { ...prettierConfig, filepath: outputPath }
);

if (check) {
  let current = "";
  try {
    current = await readFile(outputPath, "utf8");
  } catch {}

  if (current !== rendered) {
    console.error("docs/backlog/backlog.html is stale. Run npm run backlog:build.");
    process.exitCode = 1;
  } else {
    console.log("Generated backlog dashboard is current.");
  }
} else {
  await writeFile(outputPath, rendered);
  console.log("Generated docs/backlog/backlog.html.");
}
